### ISSUE TITLE
For BeautifyX / Select statements, do not always separate Group By and Order By into new lines

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/PEMEditor#40]
One of the relatively recent enhancements to BeautifyX is to have Group By and Order by fields being listed on separate lines.

This makes perfect sense when the fields are actually fields, but is less appealing when the fields are simply integer numbers.

This is the way it looks now before BeautifyX (and I would like it to remain this way after):

![image](https://github.com/VFPX/PEMEditor/assets/81179335/d905ce8b-977c-4b58-ac0d-6eadbc5f3871)

After BeautifyX is a lot less beautiful:

![image](https://github.com/VFPX/PEMEditor/assets/81179335/e696c0e1-ebe7-40de-9233-73e3cf37090d)

My suggestion is that if the Group By or Order By fields are simply numbers they do not get separated into new lines.

P.S.:  There may be a point of confusion if there is a combination of actual fields and field numbers in the same phrase.  I am unconcerned how that is handled, as I don't mix and match.

**Comment by tbleken** [comment]
I suggest that named fields are on separate lines, while numbered fields are kept on one line. I have had situations where I have upgraded applications to VFP9 from earlier versions. Instead of Set Enginebehavior 80 (or 70), I have simply added the missing fields at the end. However, I have not always bothered to name these extra fields, I have only added their numbers.

The result may look like this, which I think is fine:

Group by Field1,;
  Field2,;
  Field3, 8, 10

Tore Bleken

From: Jimrnelson ***@***.***>
Sent: fredag 26. mai 2023 13:29
To: VFPX/PEMEditor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VFPX/PEMEditor] For BeautifyX / Select statements, do not always separate Group By and Order By into new lines (Issue #40)


One of the relatively recent enhancements to BeautifyX is to have Group By and Order by fields being listed on separate lines.

This makes perfect sense when the fields are actually fields, but is less appealing when the fields are simply integer numbers.

This is the way it looks now before BeautifyX (and I would like it to remain this way after):

[image]<https://user-images.githubusercontent.com/81179335/241206443-d905ce8b-977c-4b58-ac0d-6eadbc5f3871.png>

After BeautifyX is a lot less beautiful:

[image]<https://user-images.githubusercontent.com/81179335/241206611-e696c0e1-ebe7-40de-9233-73e3cf37090d.png>

My suggestion is that if the Group By or Order By fields are simply numbers they do not get separated into new lines.

P.S.: There may be a point of confusion if there is a combination of actual fields and field numbers in the same phrase. I am unconcerned how that is handled, as I don't mix and match.

**Comment by lscheffler** [comment]
Yes, I know this was odd - in special in mixed cases. I found it a good moment to name the fields. :D   

Finally I found it not that bad, because it's clearer to me then to have the numbers in a line with commas. But this is a matter of taste.

Tores approach makes my headache, in
```
Group by Field1,;
  Field2,;
  Field3, 8, 10
```
my brain read as `Field3, Field8, ...`, i would prefer
```
Group by Field1,;
  Field2,;
  Field3,;
  8, 10
```

There is no simple, and common way out. This is why it's like it is, all on separate line or not, number or field. 

Just let's collect solutions.

**Comment by tbleken** [comment]
Lutz,
I realize that I should have used different, more realistic, field names:

Group by Lastname,;
  Firstname,;
  Zipcode,;
  State, 5,6,7

Tore Bleken

**Comment by tbleken** [comment]
I agree.

Tore Bleken

**Comment by lscheffler** [comment]
For all I remember, there is a setting that controls if the fields, for group  and order, are broken into lines at all. But this is a typical set-and-forget problem. :)

So the rule would be, if broken into lines, do not brake integers into lines.
But I think it would be more clear to start the integers on a new line.

**Comment by Jimrnelson** [comment]
My suggestion (really, my last):

Non-integer fields always appear on a line by themselves.

Thus, integer fields may be combined on the same line, but never with real fields.

**Comment by tbleken** [comment]
+1

Tore Bleken

**Comment by lscheffler** [comment]
I looked the code up.
There are two switches, controlling if items in GROUP  BY and ORDER BY will be split into separate lines or not. I will proceed like:

- If set *off*, all remains like it is, all in a line
- If set *on*, non integers will split one per line, and each group of integers into one single line containing only integers

**Comment by lscheffler** [comment]
This would end up like (just stuff fpr fields)
```
*SELECT * FROM bla INTO blu ORDER BY x,y,1,2,; &&muku
3,bl,; &&mu
ddd,fv,cc,4,8,9,22,x2,5,8;
	group BY x,y,1,2,; &&muku
3,bl,; &&mu
ddd,fv,cc,4,8,9,22,x2,5,8

Select *;
 From bla;
 Into blu ;
 Order By x,;
  Y,;
  1,2,; &&muku
  3,;
  bl,; &&mu
  ddd,;
  Fv,;
  cc,;
  4,8,9,22,;
  x2,;
  5,8;
 Group By x,;
  Y,;
  1,2,; &&muku
  3,;
  bl,; &&mu
  ddd,;
  Fv,;
  cc,;
  4,8,9,22,;
  x2,;
  5,8
```

**Comment by Jimrnelson** [comment]
Are these internal switches or visible on an options page somewhere?

> I looked the code up. There are two switches, controlling if items in GROUP BY and ORDER BY will be split into separate lines or not. I will proceed like:
> 
> * If set _off_, all remains like it is, all in a line
> * If set _on_, non integers will split one per line, and each group of integers into one single line containing only integers
> 
> Edit: Except the line is continued, and with an inline comment, then it brakes anyway.

**Comment by Jimrnelson** [comment]
Your example is what I would expect.  Looks good to me; go for it.

> This would end up like (just stuff fpr fields)
> 
> ```
> *SELECT * FROM bla INTO blu ORDER BY x,y,1,2,; &&muku
> 3,bl,; &&mu
> ddd,fv,cc,4,8,9,22,x2,5,8;
> 	group BY x,y,1,2,; &&muku
> 3,bl,; &&mu
> ddd,fv,cc,4,8,9,22,x2,5,8
> 
> Select *;
>  From bla;
>  Into blu ;
>  Order By x,;
>   Y,;
>   1,2,; &&muku
>   3,;

**Comment by lscheffler** [comment]
That's the live result from BeautifyX. The comma-at-line-start option is more tricky ....

**Comment by Jimrnelson** [comment]
That's not what I get from my BeautifyX.  Each field, integer or not, is on a separate line.

Where are these switches you mention?

**Comment by lscheffler** [comment]
LOL. Life in my dev environment.

**Comment by Jimrnelson** [comment]
LOL indeed!  Live in development!   

In any case, I look forward to this change.

**Comment by lscheffler** [comment]
Will need some time, the comma-at-line-start version formats odd for unknown reason (for years). And I found a bug with inline comments. Might be rare but it should not destroy the code.

**Comment by Jimrnelson** [comment]
Yeah, people argued with me about ever providing that feature, I don't remember anybody ever agreeing with me -- and now I don't use it either.

**Comment by lscheffler** [comment]
I guess we leave it that way until somebody complains. This is true for the inline comments as well. It looks like days of headache for something nobody uses.

**Comment by Jimrnelson** [comment]
I thought I understood that this issue was taken care of, but it seems not.  

My first test of this still has it separating numeric Group By and Order By into separate lines.

Before:

![image](https://github.com/VFPX/PEMEditor/assets/81179335/895a58c4-bbcd-4d80-aa26-2256f43e87c1)

After:

![image](https://github.com/VFPX/PEMEditor/assets/81179335/5b88690c-d028-4642-be09-e1c555d789b7)

![image](https://github.com/VFPX/PEMEditor/assets/81179335/ef8b14a5-22e5-43c5-a3db-6c28cc840283)

**Comment by lscheffler** [comment]
Odd. The version is from CFU?    
It was working - until I run CFU, see https://github.com/VFPX/Thor/issues/118.

**Comment by Jimrnelson** [comment]
I don't think the Thor "to many dos" problem is related.  That issue only seems to happen after you've done CFU.  My guess is that  CFU now leaves something wrong in the environment, but restarting VFP makes  things go back to normal.

Yes, I only get from CFU and I showed you the version number from the bottom of PEM Editor.

**Comment by lscheffler** [comment]
`Select * From bly  Group By 1,2,6,x Into mu`

Runs perfectly well to
```
Select *;
 From bly ;
 Group By 1,2,6,;
  x;
 Into mu
```

Would you mind to give me the exact code snippet from OM as text?

**Comment by lscheffler** [comment]
Found the problem. With spaces between comma and number - it breaks, without it keeps the group. Try `Select * From bly  Group By 1,2, 6,x Into mu`. Guess who does not uses spaces ...

**Comment by Jimrnelson** [comment]
It turns out I can't test that, because I use the setting for BeautifyX that always adds a space after a comma.

In any case, I'm glad you identified the problem and look forward to the having the correction.
